Traceback (most recent call last):
  File "C:\Users\halim\PycharmProjects\flaskProject\venv\SkillBox2\module_5\task_4\test_task_4.py", line 20, in test_full_context_manager
    raise Exception(self.stderr_message)
Exception: Hello stderr.txt
